
skillMetadata:
  sections:
    - name: Adrressing
      fields:
        - name: userTitle
          type: text
          label: Addressing
          value: "sir"
          placeholder: Sir
    - name: What shoud Mycroft do
      fields:
        - type: label
          label: Here should be the what mycroft would do. Separated with semi-colons.
        - name: actions
          type: text
          label: Actions
          value: "what is the weather"

